services:
  - type: web
    name: supra-bi
    env: docker
    region: frankfurt
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    rootDir: .
    autoDeploy: true
   envVars:
  - key: SECRET_KEY
    value: "JSD8f8sdF9sdF9sdf9@3JSDf93JDSF934JSDf9!"
  - key: SUPERSET_SECRET_KEY
    value: "JSD8f8sdF9sdF9sdf9@3JSDf93JDSF934JSDf9!"
  - key: ADMIN_USERNAME
    value: admin
  - key: ADMIN_PASSWORD
    value: admin
  - key: PORT
    value: "8088"
