services:
  - type: web
    name: supra-bi
    env: docker
    region: frankfurt
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    rootDir: .
    autoDeploy: true
    envVars:
      - key: SUPERSET_SECRET_KEY
        value: "SDFJ93sdjf93SDf9sdF934jsdf93JSDF934jsdf!"
      - key: SECRET_KEY
        value: "SDFJ93sdjf93SDf9sdF934jsdf93JSDF934jsdf!"
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin
      - key: PORT
        value: "8088"
